### ISSUE TITLE
Third Party directory - obsolete?

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/silo#116]
Is this still in use?
https://github.com/msmobility/silo/tree/master/third-party

**Comment by moeckel** [comment]
I doubt this is used anywhere. I find it peculiar that there is a TransCAD directory, as SILO never was linked to a TransCAD model. I might have used CUBE Voyager at some point to connect SILO to the MSTM, but this link is solved by batch files now. I believe this directory can be removed.

**Comment by nkuehnel** [comment]
fixed in f4d20fa
