### ISSUE TITLE
integrate matsim inputs into silo folder and silo.properties

### ISSUE THREAD

**Issue by cllorca1** [msmobility/silo#13]
-currently the files are: 
matsim network (or networks by year!)
skim matrix in distance (temporary for mode choice)
mode choice model (temporary, to be changed by mito)
departure and duration distributions
zone coordinates

-currently the parameters are: 
base directory
output folder
matsim iterations
matsim parallel threads
matsim scaling factor - down sampling

**Comment by cllorca1** [comment]
After 265b8a23bea711f4f4afad808dfd0450e8661d20

In branch carlos_mito2matsim the mentioned are now read within the silo working folder: 

mito additional data: input/mito
matsim-sepecific data: matsim
mito:outputs: scenOutput/mito

Lines for traffic assignment are commented in MitoTransportModel.java to pass tests.

**Comment by moeckel** [comment]
Not sure I understand the issue. I believe we want to keep the MATSim properties file separate from the SILO properties file. That is the same way we kept it with MITO.
