### ISSUE TITLE
Cannot write schools in Maryland

### ISSUE THREAD

**Issue by cllorca1** [msmobility/silo#131]
The method writeSchools crashed in Maryland implementation (school data manager is null). I temporary fixed it with if Implementation.equals(Munich) for testing but I am not sure which is the best solution for it.

**Comment by Qinnnnn** [comment]
Implementation.equals(Munich) is a temporary solution for now. All implementation-based code is going to be removed and will have the independent implementation in each use case module @nkuehnel

**Comment by nkuehnel** [comment]
@msmobility/codesprintmarch2019

**Comment by nkuehnel** [comment]
Schools are not present in maryland anymore
