### ISSUE TITLE
mito working folder when running mito from silo

### ISSUE THREAD

**Issue by cllorca1** [msmobility/silo#14]
when running mito from silo the method MitoModel >  feedData > readAdditionalData() cannot find the files. Apparently it looks for them into the silo input folder and not in the mito folder?

This is probably a change in mito rather than in silo.

**Comment by nkuehnel** [comment]
When mito is called in silo (mito.run.travel.model == true), it will look for the mito properties file that is defined in the silo properties. 

Example properties file:
mito.run.travel.model    = true
mito.properties.file	 = ./test/scenarios/annapolis/javaFiles/mito.properties

So it will link to the mito properties file where you can define the input for mito. It's not super clean yet but it works. Have a look at the siloMito test and its input.
https://github.com/msmobility/silo/tree/master/test/scenarios/annapolis/javaFiles
