### ISSUE TITLE
Create default implementations for moves/marriage and geodata reader (?)

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/silo#151]
This allows us to instantiate a default silo model and write tests for silo core

**Comment by moeckel** [comment]
Sounds good. It needs to be simple enough that is does not take up too much time to update should we make larger changes to the SILO core model, yet it should be complex enough to include most of the features that we use in Munich and are likely to be applied in other study areas as well.

**Comment by nkuehnel** [comment]
Seems to be fixed.
