### ISSUE TITLE
implement javascript for dwelling utility

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/silo#17]
see
https://wiki.tum.de/display/msm/Javascript+Implementations+for+SILO

**Comment by moeckel** [comment]
Has been completed for Munich implementation. Would be nice to add to MSTM implementation, which would allow us to delete the class relocation.MovesDMU

**Comment by moeckel** [comment]
So far, only "selectDwelling" was converted to JavaScript. "dwellingUtility" is still missing. @cllorca1 Can you fix this?
