### ISSUE TITLE
cannot resolve symbol

### ISSUE THREAD

**Issue by key2000** [msmobility/silo#172]
##Hi all,
This is Masanobu.
Sorry for disturbing with my beginner question.
Today, I have updated SILO and try to run Kagawa case, but got error with "Cannot resolve symbol "implementation" in SiloKagawa.java.
the "Implementation" is appeared in red at following line.
import de.tum.bgu.msm.Implementation;
Does anyone give me instruction how can I solve it?

Thank you!

Masanobu

**Comment by nkuehnel** [comment]
Dear Masanobu,

the SILO code has experienced some major changes that also got rid of the Implementation class.
The Kagawa use case on the master branch is unfortunately not operational right now. 
If you want to use it in the next time we would probably have to prepare the setup code for you first

Best
Nico

**Comment by key2000** [comment]
Dear Nico,

Thank you for you reply.
OK, I understand that the major revision.
I am still considering to utilize SILO for my research so I would like your team to make the Kagawa case operational. Do you think it is possible to setup the code before my visit in next July?

Thank you for your consideration.
Best regards,
Masanobu

**Comment by nkuehnel** [comment]
Dear Masanobu,

we will work on updating the Kagawa code in the next days/weeks and let you know when it is operational again :)

Looking forward to see you in July!
Best
Nico

**Comment by key2000** [comment]
Dear Nico,

Thank you very much for your message!
Yes please let me know when it gets operational.

I also look forward to seeing you and your team in July!

Best 
Masanobu

**Comment by nkuehnel** [comment]
Fixed
