### ISSUE TITLE
Issue with DefaultDwellingTypeImpl.java

### ISSUE THREAD

**Issue by moeckel** [msmobility/silo#173]
@tywellik found the following issue:

There's a java file called DefaultDwellingTypeImpl. It seems to be hard-coding acres per dwelling. If you change the file acresPerDwellingByType.csv, those changes seem to get overwritten by this java class. 

It is fine to provide a base value, but it should be possible to override these values. How about we define these values when we specify the dwellings types of a given implementation?

**Comment by nkuehnel** [comment]
Hi,
if I remember correctly, at that time, we decided to hard code the values in the enum class and put it behind an interface. If one wants to use her own values she would need to implement her own DwellingType implementation (preferably as enum as well). The RealestateDataManager expects a List of DwellingTypes in the constructor (called in the DataBuilder). I think @atmoreno did something similar for cape town:

https://github.com/msmobility/silo/blob/8e10d307ff8a5513900ff3adc651dc93d5dac0ef/useCases/capeTown/src/main/java/de/tum/bgu/msm/data/dwelling/DwellingTypeCapeTown.java#L1-L60

Is that fine for you?

**Comment by nkuehnel** [comment]
I guess this can be seen as fixed
