### ISSUE TITLE
Car ownership increase too high (?)

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/silo#177]
around 8% of all households add a new car per year, while only 1% relinquish car

might need to revise this?

**Comment by nkuehnel** [comment]
seems to be ok

**Comment by nkuehnel** [comment]
reopening this, as there are doubts

**Comment by AlonaPukhova** [comment]
![car_ownership_silo_2011-2050](https://user-images.githubusercontent.com/53340080/62695899-97f47b80-b9d7-11e9-9e48-7cc82c7b998d.png)
High increase of HH with 3 cars

2019-08-05 12:01:47,703  INFO UpdateCarOwnershipModelMuc:153   Simulated household added a car262888 (13.0% of hh)
2019-08-05 12:01:47,703  INFO UpdateCarOwnershipModelMuc:156   Simulated household relinquished a car5639 (1.0% of hh)

MITO simulation results show high increase in the number of autoDriver and privateAV trips
![MITO_mode_2011-2050](https://user-images.githubusercontent.com/53340080/62696250-4e586080-b9d8-11e9-82b5-837f7852c288.PNG)

**Comment by moeckel** [comment]
This is a very useful analysis. Could you confirm that we are using Matthew's car-owernship model? And not Maryland's?

**Comment by nkuehnel** [comment]
Yes, this is for the model in MUC. It seems like most households will keep on _adding_ new cars. In the current implementation adding does not mean replacing an old one and getting rid of cars is much less likely to happen (1% of hh per year, whereas 13% get a new one each year)

**Comment by nkuehnel** [comment]
> Could you confirm that the parameters show in this PDF are implemented correctly in the JavaScript file?
<sub>[View in Slack](https://msmobility-tum.slack.com/archives/CLCML2XLG/p1565279187021800)</sub>

**Comment by cllorca1** [comment]
Hopefully closed after pull #226
