### ISSUE TITLE
Add transit sensitivity to region choice

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/silo#246]
Transit travel times for relocation are currently only considered in the dwelling evaluation.
However, the region is chosen first. Currently transit travel times do not affect region selection. If houeholds are sensitive to transit, shouldn't they already choose a region which is accessible by transit (on average)?

**Comment by moeckel** [comment]
YES!

**Comment by moeckel** [comment]
Can we use the same method as we do for dwelling selection, where auto and transit times are averaged based on auto availability?

**Comment by nkuehnel** [comment]
Si!

**Comment by nkuehnel** [comment]
closed by #254
