### ISSUE TITLE
Find a way for deterministic multi year simulation

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/silo#30]
When more than one year is simulated, the results of silo become stochastic and not reproducable. This prevents us from relying on the [regression test](https://github.com/msmobility/silo/blob/master/src/test/java/de/tum/bgu/msm/SiloMatsimMultiYearTest.java) that @dziemke implemented for us.

We found it most probably to be  emerging from the [job updating code](https://github.com/msmobility/silo/blob/master/src/main/java/de/tum/bgu/msm/jobmography/UpdateJobs.java), which uses random numbers in parallel computation:

```
// Multi-threading code
        Function1<String,Void> JobChangeMethod = new Function1<String,Void>() {
            public Void apply(String employmentChangeDefinition) {
                String[] change = employmentChangeDefinition.split(":");
                if (change[0].equalsIgnoreCase("add")) {
                    addJobs(change[1]);
                } else {              // token "rem"
                    removeJobs(change[1], dataContainer);
                }
                return null;
            }
        }
```

As threads are running in random order, the random numbers are not drawn in the same order in each run.

- maybe we can find a way to distribute the same random numbers to each thread for every run 

or 

~~- implement a sequential version of the computation which can be turned on for testing.~~

**Comment by nkuehnel** [comment]
Actually there is no access to the random object. It's rather that the static method

   ```
public static int getNextJobId () {
        // increase highestJobIdInUse by 1 and return value
        highestJobIdInUse++;
        return highestJobIdInUse;
    }
```

is called in random order depending on the order of access of threads. Will try to assign ids in advance.

**Comment by nkuehnel** [comment]
Job update is now deterministic (ef9d9f5) 
Now population files are still different:
the income seems to be randomized over the years

**Comment by nkuehnel** [comment]
Another multi thread code:
```
 public void adjustIncome() {
        // select who will get a raise or drop in salary

        currentIncomeDistribution = calculateIncomeDistribution();   // income by gender, age and unemployed/employed
        Integer[] personArray = new Integer[Person.getPersonCount()];
        Person[] pps = Person.getPersonArray();
        for (int per = 0; per < pps.length; per++) personArray[per] = pps[per].getId();

        // Multi-threading code
        Function1<Integer, Void> incomeChangeFunction = new Function1<Integer, Void>() {
            public Void apply(Integer per) {
                adjustIncomeForPerson(per);
                return null;
            }
        };
//
        Iterator<Integer> incomeChangeIterator = ArrayUtil.getIterator(personArray);
        IteratorAction<Integer> itTask = new IteratorAction<>(incomeChangeIterator, incomeChangeFunction);
        ForkJoinPool pool = ForkJoinPoolFactory.getForkJoinPool();
        pool.execute(itTask);
        itTask.waitForCompletion();
    }
```

**Comment by cllorca1** [comment]
Does this property change anything?

System.setProperty("java.util.concurrent.ForkJoinPool.common.parallelism", "0")

**Comment by nkuehnel** [comment]
Unfortunately not - the order of accessing the random object is still not defined :/

**Comment by nkuehnel** [comment]
@dziemke it works now :)
