### ISSUE TITLE
Error showing in SiloMatsim for Maryland 

### ISSUE THREAD

**Issue by mhchayan** [msmobility/silo#309]
Hi Nico,

I am facing a problem when trying to run the SiloMatsim for Maryland. The following error is showing. Can you please help with this? Thanks.

Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	Illegal modifier for parameter properties; only final is permitted
	Illegal modifier for parameter matsimConfig; only final is permitted
	SiloMatsim.String cannot be resolved to a type
	Syntax error on token "(", . expected
	Duplicate local variable args
	Illegal modifier for parameter args; only final is permitted
	Syntax error on token ",", ; expected
	Syntax error on token ")", ; expected
	void[] is an invalid type
	Syntax error on token "run", AnnotationName expected after this token
	Illegal modifier for parameter run; only final is permitted
	Syntax error, insert "[ ]" to complete Dimension
	Syntax error, insert ";" to complete LocalVariableDeclarationStatement

	at de.tum.bgu.msm.run.SiloMatsim.main(SiloMatsim.java:20)

**Comment by nkuehnel** [comment]
hi,

this looks like a bunch of compilation problems...did you write/adapt the class yourself? Did you set your JDK correctly?

**Comment by mhchayan** [comment]
Hi Nico,

No, I did not write the class myself. It was from the github. I was running SiloMstm first. This problem shows in SiloMatsim, Maryland, and also I see in the Fabiland (Maybe to create shapefile class, I didn't use that) code.

Regarding the JDK, I am using JDK 1.8.0_212 which was fine SiloMstm. Do I need to change that? Let me know. Thanks.


-Mahmudul

**Comment by nkuehnel** [comment]
Hi Mahmudul,

could you try using a Java 11 JDK?
