### ISSUE TITLE
Models details of Silo

### ISSUE THREAD

**Issue by mhchayan** [msmobility/silo#310]
Hi Nico,

I was running SiloMstm. I would like to know how the probability was calculated 
( https://github.com/msmobility/silo/tree/master/siloCore/src/main/resources/de/tum/bgu/msm/models). Can I use the same probability for Maryland? Is there any published paper on details of which models are used Silo? If so, can you please give me the link of those papers? Thanks!

Regards
Mahmudul

**Comment by nkuehnel** [comment]
Hi @mhchayan ,
the models are not all equally well-calibrated. However, as SILO was originally developed for Maryland, most of the models should be compatible with the Maryland implementation. 

Please visit silo.zone for some more information. There are also a few publications that might help you:
http://silo.zone/publications.html

Best
Nico
