### ISSUE TITLE
Job map update error after using concurrent infrastructure

### ISSUE THREAD

**Issue by atmoreno** [msmobility/silo#33]
After daf0d4ebca7f30cdf0b31903d9b3864bbc4b46e5, that adjusted updateJobs to use the new concurrent infrastructure, summarizeJobs method produces an error on the second SILO simulation year. If I revert the commit, summarizeJobs performs well for the complete SILO simulation period. 

Any thoughts?

**Comment by nkuehnel** [comment]
That seems to be randomly occuring. I will look into that - Thanks for the hint
