### ISSUE TITLE
Any document for SILO-MATSim intergrated ?

### ISSUE THREAD

**Issue by sinkan851014** [msmobility/silo#330]
I am a graduate student trying to do simulation by SILO-MATSim.
There are lots of lesson and resource for me to learn how to use MATSim step by step,but unfortunately SILO was opposite.
Since I just start my JAVA lesson a month ago,could anyone share some source(SILO Model) for me? 
Even couldn't find the "SILO-MATSim_Installation.docx" mentioned in the readme .
Thanks a lot also apperciate.

**Comment by moeckel** [comment]
We can provide you with a dataset to run SILO. Where are you based? I wonder whether a Germany-based (Munich) or a US-based (Maryland) would work better for you. 

@nkuehnel: Can you provide the file "SILO-MATSim_Installation.docx"?

**Comment by nkuehnel** [comment]
Hi,

the "SILO-MATSim_Installation.docx" file no longer exists as it was outdated. With the recent code it should be as simple as checking the ode out as a maven project and everything should be set up.

**Comment by sinkan851014** [comment]
Thanks for your help!
The location I simulate might select the city in Taiwan. (depend on discussing with my professor)
I would keep testing how to step up. Maybe I should start with realizing more Java basics first.

**Comment by moeckel** [comment]
Sounds good, keep us posted. Once you are ready, you can contact me and we will provide you with input data for an existing model implementation. It will be good to get the basics of Java under your belt. Let us know when you have decided on a study area.
