### ISSUE TITLE
microdata file definition

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/silo#36]
in summarizeData.java there are 4 writeOutSyntheticPopulationDe methods, some of them with different header information.

Do we need all 4 of them? Which one is the default to use? (for example, in one method, education is a person attribut. In an other it's not)

**Comment by moeckel** [comment]
@atmoreno Can you answer this question? Thanks!

**Comment by nkuehnel** [comment]
used for different implementations / level of details
