### ISSUE TITLE
Time dependent travel times

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/silo#69]
In addition to the flexible MATSim query approach, we could create matrices (e.g. for every hour) to satisfy the TravelTimes interface asking also for time:
 
[`double getTravelTime(int origin, int destination, double timeOfDay_s);`](https://github.com/msmobility/mito/blob/master/src/main/java/de/tum/bgu/msm/data/travelTimes/TravelTimes.java)

**Comment by moeckel** [comment]
How much runtime would it require to create 24 matrices? How much memory (RAM) does it take to store those? Or maybe 18 matrices would be enough, as the night hours will be almost identical.

**Comment by nkuehnel** [comment]
the new matrix library does support 3 dimensional arrays  which would ease handling the data. 
need to check for memory but creation should not be a runtime issue, as those are still the skim matrices provided as input

**Comment by cllorca1** [comment]
A 24 hour matrix (24 matrices) is  1.7 GB and will be ready for tomorrow. We can reduce the number of different hours once seen how it looks like.

**Comment by nkuehnel** [comment]
from parallel colt matrix documentation (dense implementation):

> Implementation:
> 
> Internally holds one single contigous one-dimensional array, addressed in row major. Note that this implementation is not synchronized.
> 
> Memory requirements:
> 
> memory [bytes] = 8*rows()*columns(). Thus, a 1000*1000 matrix uses 8 MB.

For ~5000 zones its 5000*5000*8 ~200MB of RAM for one matrix.
