### ISSUE TITLE
Unnecessary(?) calculation of zonal foreigner share

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/silo#71]
In MovesModelMuc there is a method:
`calculateShareOfForeignersByZoneAndRegion`

inside the method the zonal share of foreigners is calulated but it is neither stored nor is it used by any subsequent model/calculation. Is this a bug or can we remove the zonal share part of this method?

**Comment by moeckel** [comment]
@nkuehnel Good catch. I believe we wrote this method when we started transferring the model to Munich. In Maryland, we had a method `calculateRacialCompositionByZoneAndRegion()`. As race is not really relevant in Germany, we just renamed it to `calculateShareOfForeignersByZoneAndRegion()`. 
@atmoreno Ana, you were asked to update the method `calculateRegionalUtilities()`. For now, I would leave this method `calculateShareOfForeignersByZoneAndRegion()` in the code (we can comment it out for now) and wait until Ana decided what she needs for `calculateRegionalUtilities()`.

**Comment by atmoreno** [comment]
As @moeckel recalls, we wrote the method when we transferred the model to Munich. Although racial seggregation does not play a role in Munich, we still thought that nationality seggregation could be significant in some zones. Therefore, we wrote the method in terms of nationality. 
The excel UEC model has "share of foreigners" as variable. It should be a bug if the variable is not set as well inside the JavaScript.

**Comment by nkuehnel** [comment]
Regional share is a variable in the uec and the javascript. zonal share, however is not. In mstm the zonal share is used after the calculation of the dwelling utility to adjust it:

`if (householdRace != Race.other) {
                racialShare = getZonalRacialShare(geoData.getZones().get(dd.getZone()).getId(), householdRace);
            }
            // multiply by racial share to make zones with higher own racial share more attractive
            double adjProb;
            if (householdQualifiesForSubsidy(householdIncome, geoData.getZones().get(dd.getZone()).getId(), dd.getPrice())) {
                adjProb = Math.pow(calculateDwellingUtilityOfHousehold(ht, householdIncome, dd, siloModelContainer), (1 - selectDwellingRaceRelevance)) *
                        Math.pow(racialShare, selectDwellingRaceRelevance);
            }`

**Comment by nkuehnel** [comment]
The actual issue was that we caculate both, zonal an dregional share in Muc, but only use the regional (yet) :)

**Comment by atmoreno** [comment]
Ok! Thanks for the clarification @nkuehnel. To make it consistent with Mstm, we can keep the zonal foreigner share for now and add the adjustment factor on dwelling utility as well.

**Comment by nkuehnel** [comment]
@msmobility/codesprintmarch2019

**Comment by nkuehnel** [comment]
this seems to have been removed/fixed/forgotten at some point.

**Comment by moeckel** [comment]
@nkuehnel I appreciate so much that you are cleaning up these outdated issues. Thanks!
