### ISSUE TITLE
Accessibility Calculation twice per year

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/silo#83]
accessibiity in silo model is calulcated up to twice times per year - once when transport model runs and another time when skims are updated. in between those two calculations micro events are simulated. do we need to calculate it (up to) twice times per year?

**Comment by moeckel** [comment]
@nkuehnel Can you remove the accessibility calculation after the transport model ran? However, we need to make sure that accessibilities are updated every time new skims are provided (which in our case is after the transport model ran, in Maryland it is every year when new skims are provided (as specified in the properties file).

**Comment by cllorca1** [comment]
Accesibility is now calculated only once per year.
