### ISSUE TITLE
removing a person from a household right after being added (MarryModel) 

### ISSUE THREAD

**Issue by cllorca1** [msmobility/silo#85]
This piece of code in the method marryCouple removes persons right after adding them to newHh      
```
householdData.addPersonToHousehold(partner1, newHh);
householdData.addPersonToHousehold(partner2, newHh);
householdData.removePersonFromHousehold(partner1);
householdData.removePersonFromHousehold(partner2);
```
Throws a NullPoint. exception in the method removePersonFromHousehold when running with Munich implementation
Maybe change the order: 
```
householdData.removePersonFromHousehold(partner1);
householdData.addPersonToHousehold(partner1, newHh);
householdData.removePersonFromHousehold(partner2);
householdData.addPersonToHousehold(partner2, newHh)      
           
```

**Comment by nkuehnel** [comment]
doesn't make sense, indeed. Seems like the [MarryDivorceModelTest](https://github.com/msmobility/silo/blob/master/src/test/java/de/tum/bgu/msm/models/demography/MarryDivorceModelTest.java) does not capture this...
